default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>


development:
  <<: *default
  database: notification_app_development
  url: <%= ENV.fetch("DATABASE_URL") %>
